SET NOCOUNT ON;

-- One-time import: desktop's accAccountHead (4808 rows, all 4 real branches) -> new
-- independent WebAccountHead table. Desktop's own AccGroupCode/faAccountGroup hierarchy is
-- branch-specific and much deeper than our 27-row Tally Standard Primary Group set, so every
-- leaf group name is mapped down to the closest matching Primary Group. Names with no group
-- match (orphaned/deleted group codes) fall back to Suspense Account for manual reclassification.
-- Desktop's own tables are only READ here, never modified.

INSERT INTO WebAccountHead (HeadName, GroupCode, BranchCode, OpeningBalance, OpeningBalanceType, Remarks, IsActive, CreatedBy, CreatedAt)
SELECT
    LTRIM(RTRIM(h.AccountHead)),
    CASE UPPER(LTRIM(RTRIM(ISNULL(g.GroupName, ''))))
        -- Assets
        WHEN 'ADVANCES TO EMPLOYEES' THEN 25
        WHEN 'ASSETS' THEN 6
        WHEN 'BANK ACCOUNTS' THEN 22
        WHEN 'COFFEE MACHINE' THEN 4
        WHEN 'COMPUTERS' THEN 4
        WHEN 'CURRENT ASSETS' THEN 6
        WHEN 'DEPOSITS (ASSET)' THEN 24
        WHEN 'FIXED ASSETS' THEN 4
        WHEN 'INTERCOMPANY' THEN 25
        WHEN 'INVESTMENT' THEN 5
        WHEN 'LOANS & ADVANCES (ASSET)' THEN 25
        WHEN 'MOBILES' THEN 4
        WHEN 'NISSAN PICKUP' THEN 4
        WHEN 'NISSAN URVAN - 86156 (14884)' THEN 4
        WHEN 'OFFICE FURNITURE & EQUIPMENT' THEN 4
        WHEN 'PREPAID EXPENSES' THEN 25
        WHEN 'PREPAYMENT - TRADE LICENSE' THEN 25
        WHEN 'PREPAYMENTS - INSURANCE' THEN 25
        WHEN 'PREPAYMENTS - RENTAL EXPENSES' THEN 25
        WHEN 'PRINTERS' THEN 4
        WHEN 'RETENTION RECEIVABLE' THEN 25
        WHEN 'SECURITY DEPOSITS - ELECTRICITY & WATER' THEN 24
        WHEN 'STAFF CASH' THEN 23
        WHEN 'STOCK-IN-HAND' THEN 26
        WHEN 'SUNDRY DEBTORS' THEN 27
        WHEN 'TOOLS & EQUIPMENTS - ASSETS' THEN 4
        WHEN 'VEHICLES' THEN 4
        -- Equity
        WHEN 'CAPITAL ACCOUNT' THEN 1
        WHEN 'CURRENT ACCOUNTS' THEN 1
        WHEN 'RESERVES & SURPLUS' THEN 1
        -- Liabilities
        WHEN 'ACCRUED EXPENSES' THEN 3
        WHEN 'CURRENT LIABILITIES' THEN 3
        WHEN 'DUTIES & TAXES' THEN 19
        WHEN 'INTEREST PAYABLES' THEN 3
        WHEN 'LIABILITIES' THEN 3
        WHEN 'LOANS - LIABILITY' THEN 17
        WHEN 'PROVISIONS' THEN 20
        WHEN 'PROVISIONS FOR AIR FARE' THEN 20
        WHEN 'PROVISONS FOR GRATUITY' THEN 20
        WHEN 'SALARY PAYABLES - MANAGEMENT' THEN 3
        WHEN 'SUB-CONTRACTORS' THEN 21
        WHEN 'SUNDRY CREDITORS' THEN 21
        WHEN 'SUNDRY CREDITORS - PURCHASE' THEN 21
        WHEN 'SUNDRY CREDITORS -EMD DEPARTMENT' THEN 21
        WHEN 'SUSPENSE A/C' THEN 9
        WHEN 'UNSECURED LOANS' THEN 18
        -- Income
        WHEN 'DIRECT INCOMES' THEN 12
        WHEN 'INDIRECT INCOMES' THEN 13
        WHEN 'PROFIT OF SALE VEHICLES' THEN 13
        WHEN 'SALES ACCOUNTS' THEN 10
        WHEN 'WAGES MANPOWER' THEN 10
        -- Expenses - direct
        WHEN 'DIRECT EXPENSES' THEN 14
        WHEN 'JOB MATERIALS' THEN 14
        WHEN 'PURCHASE ACCOUNTS' THEN 11
        WHEN 'PURCHASE@5%' THEN 11
        -- Expenses - everything else falls to Indirect Expenses
        WHEN 'ADMIN EXPENSES' THEN 15
        WHEN 'ADMIN EXPENSES - OFFICE' THEN 15
        WHEN 'AIR CONDITIONERS - LABOUR CAMP' THEN 15
        WHEN 'AIR FARE' THEN 15
        WHEN 'AIR FARE EXPENSES' THEN 15
        WHEN 'AUDIT FEES' THEN 15
        WHEN 'BUSINESS PROMOTION -ADVERTISEMENT' THEN 15
        WHEN 'CALIBRATION & TESTING' THEN 15
        WHEN 'CAMP EXPENSES & MAINTENANCE' THEN 15
        WHEN 'CARRIAGE INWARDS' THEN 15
        WHEN 'CERTIFICATE CLEARANCE & ATTESTATION' THEN 15
        WHEN 'CERTIFICATE CLEARENCE & ATTESTATION' THEN 15
        WHEN 'CNIA EXPENSES' THEN 15
        WHEN 'COMMISSION PAID' THEN 15
        WHEN 'CONSULTATION FEE PAID' THEN 15
        WHEN 'CONSUMABLES' THEN 15
        WHEN 'CONVEYNACE' THEN 15
        WHEN 'DEPRECIATION - TOOLS & EQUIPMENTS' THEN 15
        WHEN 'DEPRECIATION - VEHICLES' THEN 15
        WHEN 'DEPRECIATION OFFICE EQUIPMENTS' THEN 15
        WHEN 'ELECTRICITY & WATER - OFFICE' THEN 15
        WHEN 'ELECTRICITY & WATER EXPENSES' THEN 15
        WHEN 'EMBASSY' THEN 15
        WHEN 'ENTERTAINMENT EXPENSES' THEN 15
        WHEN 'FINANCE COST' THEN 15
        WHEN 'FINES & PENALTIES' THEN 15
        WHEN 'FOOD EXPENSES' THEN 15
        WHEN 'FOOD EXPENSES - STAFF' THEN 15
        WHEN 'FOOD EXPENSES - TRAINNING' THEN 15
        WHEN 'FUEL EXPENSES' THEN 15
        WHEN 'FUEL EXPENSES - JOBS' THEN 15
        WHEN 'GATE / PORT PASS' THEN 15
        WHEN 'GRATUITY EXPENSES' THEN 15
        WHEN 'INDIRECT EXPENSES' THEN 15
        WHEN 'INSURANCE' THEN 15
        WHEN 'INTEREST PAID' THEN 15
        WHEN 'LABOUR CAMPS - RENT' THEN 15
        WHEN 'LEAVE SALARY EXPENSES' THEN 15
        WHEN 'LEGAL & PROFESSIONAL EXPENSES' THEN 15
        WHEN 'LOSS ON SALE OF FIXED ASSETS' THEN 15
        WHEN 'MACHINERY & EQUIPMENT TESTING' THEN 15
        WHEN 'MACHINERY - HIRE EXPENSES' THEN 15
        WHEN 'MACHINERY - REPAIR & SERVICES' THEN 15
        WHEN 'MACHNINERY ACCESSORIES' THEN 15
        WHEN 'MEDICAL EXPENSES' THEN 15
        WHEN 'MOBILE ACCESSORIES' THEN 15
        WHEN 'OFFICE EXPENSES' THEN 15
        WHEN 'PRINTING & STATIONERY' THEN 15
        WHEN 'PROCESSING FEE' THEN 15
        WHEN 'RENTAL EXPENSES' THEN 15
        WHEN 'REPAIRS & SERVICES' THEN 15
        WHEN 'SAFETY ITEMS' THEN 15
        WHEN 'SALARIES & WAGES' THEN 15
        WHEN 'SITE TOOLS & EQUIP.' THEN 15
        WHEN 'SITE TOOLS & EQUIPMENT' THEN 15
        WHEN 'STAFF CAMPS - RENT' THEN 15
        WHEN 'STAFF WELFARE EXPENSES' THEN 15
        WHEN 'SUNDRY EXPENSES' THEN 15
        WHEN 'TAX' THEN 15
        WHEN 'TELEPHONE & INTERNET' THEN 15
        WHEN 'TENDER DOCUMENTS' THEN 15
        WHEN 'THIRD PARTY LIABILITY' THEN 15
        WHEN 'TRAINING & DEVELOPMENT' THEN 15
        WHEN 'TRANSPORTATION EXP. - HIRE' THEN 15
        WHEN 'TRANSPORTATION EXPENSES' THEN 15
        WHEN 'TRAVELLING EXPENSES -  FOREIGN' THEN 15
        WHEN 'VEHICLE - 86156' THEN 15
        WHEN 'VEHICLE EXPENSES' THEN 15
        WHEN 'VEHICLE RENEWALS' THEN 15
        WHEN 'VEHICLE TESTING & INSPECTION' THEN 15
        WHEN 'VISA EXPENSES' THEN 15
        WHEN 'WAGES - MANPOWER (HIRE)' THEN 15
        WHEN 'WORKMEN COMPENSATION' THEN 15
        ELSE 9  -- unmapped / orphaned group code -> Suspense Account, for manual reclassification
    END,
    h.BranchCode,
    0,
    'Dr',
    'Imported from desktop AccountCode ' + CAST(h.Accountcode AS VARCHAR(20)) +
        CASE WHEN g.GroupName IS NULL THEN ' (original group code ' + CAST(h.AccGroupCode AS VARCHAR(20)) + ' not found - please reclassify)' ELSE '' END,
    CASE WHEN h.BlockAccountYesNo = 'Y' THEN 0 ELSE 1 END,
    8,
    GETDATE()
FROM accAccountHead h
LEFT JOIN faAccountGroup g ON g.GroupCode = h.AccGroupCode
WHERE NOT EXISTS (
    SELECT 1 FROM WebAccountHead w
    WHERE w.BranchCode = h.BranchCode
      AND UPPER(LTRIM(RTRIM(w.HeadName))) = UPPER(LTRIM(RTRIM(h.AccountHead)))
);

SELECT @@ROWCOUNT AS RowsInserted;
